apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucm-producer-deployment
  labels:
    app: ucm-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucm-producer
  template:
    metadata:
      labels:
        app: ucm-producer
    spec:
      serviceAccountName: starlight-sa
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim-producer
      containers:
      - image: quay.io/rh-ee-kromashk/ucm-producer
        name: watcher-producer
        workingDir: /processing_data/
        command: ["ucm"]
        args: ["watcher", "producer"]
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: BATCH_SIZE
          value: "5"
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_REGION
          value: "de"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: EXPLORED_STARLIGHT
          value: "starlight/input"
        - name: EXPLORED_PPFX
          value: "ppfx/input"
        - name: EXPLORED_STECKMAP
          value: "steckmap/input"
        - name: PROCESSED_STARLIGHT
          value: "starlight/processed"
        - name: PROCESSED_PPFX
          value: "ppfx/processed"
        - name: PROCESSED_STECKMAP
          value: "steckmap/processed"
        - name: OUTPUT_STARLIGHT
          value: "starlight/output"
        - name: OUTPUT_PPFX
          value: "ppfx/output"
        - name: OUTPUT_STECKMAP
          value: "steckmap/output"
        - name: TEMPLATE_IN_FILE_PATH
          value: "/docker/starlight/config_files_starlight/grid_example.in"
        - name: "IN_FILE_OUTPUT_PATH"
          value: "/processing_data/starlight/runtime/infiles/"
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
      - image: quay.io/rh-ee-kromashk/ac3-connector-http-http-consumer:latest
        name: consumer
        env:
        - name: WEB_BASE_URL
          value: "http://192.168.1.10"
        - name: WEB_HTTP_PORT
          value: "28180"
        - name: WEB_HTTP_MANAGEMENT_PORT
          value: "28181"
        - name: WEB_HTTP_PROTOCOL_PORT
          value: "28182"
        - name: WEB_HTTP_CONTROL_PORT
          value: "28183"
        ports:
        - containerPort: 28180
        - containerPort: 28181
        - containerPort: 28182
        - containerPort: 28183
      - image: quay.io/rh-ee-kromashk/ucm-receiver
        name: receiver-producer
        workingDir: /processing_data/
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
        command: ["ucm"]
        args: ["consumer", "producer"]
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: AWS_ACCESS_KEY_ID
          value: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
        - name: AWS_SECRET_ACCESS_KEY
          value: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
        - name: S3_ENDPOINT
          value: "https://s3.eu-central-1.ionoscloud.com"
        - name: S3_REGION
          value: "de"
        - name: S3_BUCKET_NAME
          value: "test-consumer"
        - name: IN_FILE_PATH
          value: "/processing_data/starlight/runtime/infiles"
        - name: PROCESS_LIST
          value: "/processing_data/starlight/runtime/processlist.txt" 
        - name: OUTPUT_BUCKET_STARLIGHT
          value: "starlight/output"
        - name: OUTPUT_BUCKET_PPFX
          value: "ppfx/output"
        - name: OUTPUT_BUCKET_STECKMAP
          value: "steckmap/output"
