# ==========================
# ConfigMap
# ==========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: ucm-processor-config
  namespace: uc3-applications
data:
  # RabbitMQ
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  # S3
  S3_ENDPOINT: https://s3.eu-central-1.ionoscloud.com
  S3_REGION: de
  S3_BUCKET_NAME: test-consumer

  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""

  # Processing
  JOB_SIZE: "5"
  BATCH_INFO_DIR: /processing_data/batch_info
  IN_FILE_OUTPUT_PATH: /processing_data/starlight/runtime/infiles
  TEMPLATE_IN_FILE_PATH: /docker/starlight/config_files_starlight/grid_example.in

  # STARLIGHT
  INPUT_DIR_STARLIGHT: /processing_data/starlight/data/input
  EXPLORED_DIR_STARLIGHT: /processing_data/starlight/data/output
  PROCESSED_STARLIGHT: /processing_data/starlight/data/processed
  PROCESS_LIST_STARLIGHT_PATH: /processing_data/starlight/runtime

  # PPXF
  INPUT_DIR_PPXF: /processing_data/ppxf/data/input
  EXPLORED_DIR_PPXF: /processing_data/ppxf/data/output
  PROCESSED_PPXF: /processing_data/ppxf/data/processed
  PROCESS_LIST_PPXF_PATH: /processing_data/ppxf/runtime

  # STECKMAP
  EXPLORED_DIR_STECKMAP: /processing_data/steckmap/data/input
  OUTPUT_DIR_STECKMAP: /processing_data/steckmap/data/output
  PROCESSED_STECKMAP: /processing_data/steckmap/data/processed
---
# ==========================
# Secret 
# ==========================
apiVersion: v1
kind: Secret
metadata:
  name: ucm-processor-secrets
  namespace: uc3-applications
type: Opaque
stringData:
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  AWS_ACCESS_KEY_ID: "EEAAAAHuEn6LkwZJGpUAikGoJHyOrAra4yXAV1WVXpvA8XU0HAAAAAEB7vvNAAAAAAHu-80YrfBIAbZ4Ef4idjOF9BTQ"
  AWS_SECRET_ACCESS_KEY: "D3c2ApVsGGa7Wm1+pmfDwJddoPxhY3qSwU1U2EUUyKJRE07H3MjR3nwwaxim7mhY"
---
# ==========================
# Deployment
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucm-processor
  namespace: uc3-applications
  labels:
    app: ucm-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucm-processor
  template:
    metadata:
      labels:
        app: ucm-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: starlight-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: processing-storage
          persistentVolumeClaim:
            claimName: ucm-pv-claim

      containers:
        # --- STARLIGHT ---
        - name: starlight
          image: quay.io/bcapper30/starlight:latest
          workingDir: /docker/starlight/STARLIGHTv04
          command: ["./bash_script2.sh"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROCESS_LIST_STARLIGHT
              value: "/processing_data/starlight/runtime/processlist-$(POD_NAME).txt"
            - name: PROCESS_LIST_STARLIGHT_PATH
              valueFrom:
                configMapKeyRef:
                  name: ucm-processor-config
                  key: PROCESS_LIST_STARLIGHT_PATH
          volumeMounts:
            - name: processing-storage
              mountPath: /processing_data/
          securityContext:
            privileged: true

        # --- Receiver ---
        - name: receiver
          image: quay.io/rh-ee-kromashk/uc3-backend:latest
          workingDir: /processing_data/
           command: ["/usr/bin/ucm", "consumer", "processor"] 
          envFrom:
            - configMapRef:
                name: ucm-processor-config
            - secretRef:
                name: ucm-processor-secrets
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROCESS_LIST_STARLIGHT
              value: "/processing_data/starlight/runtime/processlist-$(POD_NAME).txt"
            - name: PROCESS_LIST_PPXF
              value: "/processing_data/ppxf/runtime/processlist-$(POD_NAME).txt"
            - name: PROCESS_LIST_STARLIGHT_PATH
              valueFrom:
                configMapKeyRef:
                  name: ucm-processor-config
                  key: PROCESS_LIST_STARLIGHT_PATH
            - name: PROCESS_LIST_PPXF_PATH
              valueFrom:
                configMapKeyRef:
                  name: ucm-processor-config
                  key: PROCESS_LIST_PPXF_PATH
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: processing-storage
              mountPath: /processing_data/
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

        # --- Watcher --- 
        - name: watcher
          image: quay.io/rh-ee-kromashk/uc3-backend:latest
          workingDir: /processing_data/
          command: ["/usr/bin/ucm", "watcher", "processor"]
          envFrom:
            - configMapRef:
                name: ucm-processor-config
            - secretRef:  
                name: ucm-processor-secrets
          env:
            - name: POD_NAME 
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: processing-storage
              mountPath: /processing_data/
          securityContext:
            privileged: true

        # --- PPXF ---
        - name: ppxf
          image: quay.io/bcapper30/uc3-ppxf:latest
          workingDir: /processing_data/
          command: ["/home/ppxf/ppxf_script.sh"]
          envFrom:
            - configMapRef:
                name: ucm-processor-config
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: API_URL
              value: "http://uc3-backend-service:8080/api/progress/update"
            - name: PROCESS_LIST_PPXF
              value: "/processing_data/ppxf/runtime/processlist-$(POD_NAME).txt"
          volumeMounts:
            - name: processing-storage
              mountPath: /processing_data/
          securityContext:
            privileged: true
---
# ==========================
# Service
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: ucm-processor-service
  namespace: uc3-applications
  labels:
    app: ucm-processor
    svc: ucm
spec:
  selector:
    app: ucm-processor
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# ==========================
# ServiceMonitor 
# ==========================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ucm-processor-monitor
  namespace: uc3-applications
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ucm-processor
  namespaceSelector:
    matchNames:
      - uc3-applications
  endpoints:
    - port: http
      interval: 15s
      path: /metrics