apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucm-producer-deployment
  namespace: uc3-applications
  labels:
    app: ucm-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucm-producer
  template:
    metadata:
      labels:
        app: ucm-producer
    spec:
      serviceAccountName: starlight-sa
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim-producer
      containers:
      - image: quay.io/rh-ee-kromashk/uc3-backend:latest
        name: watcher-producer
        workingDir: /processing_data/
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "watcher", "producer"]
        envFrom:
        - configMapRef:
            name: uc3-shared-config
        - secretRef:
            name: uc3-shared-secrets
        ports:
        - containerPort: 5672
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
      - image: quay.io/rh-ee-kromashk/uc3-backend:latest
        name: http-server
        workingDir: /processing_data/
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "server"]
        envFrom:
        - configMapRef:
            name: uc3-shared-config
        - secretRef:
            name: uc3-shared-secrets
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
      - image: quay.io/rh-ee-kromashk/uc3-backend:latest
        name: receiver-producer
        workingDir: /processing_data/
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "consumer", "producer"]
        envFrom:
        - configMapRef:
            name: uc3-shared-config
        - secretRef:
            name: uc3-shared-secrets
      - image: quay.io/rh-ee-kromashk/uc3-backend:latest
        name: aggregator
        workingDir: /processing_data/
        ports:
        - containerPort: 9090
          protocol: TCP
          name: metrics
        volumeMounts:
        - mountPath: /processing_data/
          name: ucm-pv-storage
        securityContext:
          privileged: true
        command: ["/uid_entrpoint.sh"]
        args: ["/usr/bin/ucm", "aggregator"]
        envFrom:
        - configMapRef:
            name: uc3-shared-config
        - secretRef:
            name: uc3-shared-secrets
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
          