# ==========================
# RBAC Resources for UC3 Application
# ==========================
# Service Account for Privileged Workloads
# ==========================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starlight-sa
  namespace: uc3-applications
---
# ==========================
# RoleBinding for Privileged SCC
# ==========================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-role
  namespace: uc3-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: starlight-sa
  namespace: uc3-applications
---
# ==========================
# Service Account for Monitoring
# ==========================
kind: ServiceAccount
apiVersion: v1
metadata:
  name: uc3-monitoring
  namespace: uc3-applications
---
# ==========================
# ClusterRoleBinding for Monitoring
# ==========================
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: uc3-monitoring-cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: uc3-monitoring
    namespace: uc3-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view

