apiVersion: v1
kind: Service
metadata:
  name: uc3-backend-service
  namespace: uc3-applications
  labels:
    app: ucm-producer
spec:
  selector:
    app: ucm-producer
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: uc3-backend-api
  namespace: uc3-applications
  labels:
    app: ucm-producer
spec:
  to:
    kind: Service
    name: uc3-backend-service
  port:
    targetPort: api
  tls:
    termination: edge 