apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.17.2
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "test-token"
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"  
          limits:
            memory: "2Gi"
            cpu: "1"     
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
  - name: vault
    port: 8200
    targetPort: 8200
  type: ClusterIP

