apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlight
  labels:
    app: starlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlight
  template:
    metadata:
      labels:
        app: starlight
    spec:
      serviceAccountName: starlight-sa
      volumes:
      - name: ucm-pv-storage
        persistentVolumeClaim:
          claimName: ucm-pv-claim
      containers:
      - image: quay.io/rh-ee-kromashk/ucm-starlight
        name: starlight
        workingDir: /docker/starlight/STARLIGHTv04
        command: ["./bash_script2.sh"]
        volumeMounts:
        - mountPath: /processing/
          name: ucm-pv-storage
      - image: quay.io/rh-ee-kromashk/ucm-receiver
        name: eventreceiver
        volumeMounts:
        - mountPath: /processing/
          name: ucm-pv-storage
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: IN_FILE_PATH
          value: "/processing/starlight/runtime/infiles"
        - name: PROCESS_LIST
          value: "/processing/starlight/runtime/processlist.txt" 
        - name: INPUT_DIR_STARLIGHT
          value: "/processing/starlight/data/input"
        - name: INPUT_DIR_PPFX
          value: "/processing/ppfx/data/input"
        - name: INPUT_DIR_STECKMAP
          value: "/processing/steckmap/data/input"
        - name: OUTPUT_DIR_STARLIGHT
          value: "/processing/starlight/data/output"
        - name: OUTPUT_DIR_PPFX
          value: "/processing/ppfx/data/output"
        - name: OUTPUT_DIR_STECKMAP
          value: "/processing/steckmap/data/output"
      - image: quay.io/rh-ee-kromashk/ucm-watcher
        name: ucm-watcher
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /processing/
          name: ucm-pv-storage
        env:
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: OUTPUT_DIR_STARLIGHT
          value: "/processing/starlight/data/output"
        - name: OUTPUT_DIR_PPFX
          value: "/processing/ppfx/data/input"
        - name: OUTPUT_DIR_STECKMAP
          value: "/processing/steckmap/data/input"
        - name: BATCH_SIZE
          value: "5"
        ports:
        - containerPort: 5672