# ---------- Stage 1: Build ----------
      FROM docker.io/library/golang:1.23 AS builder
      WORKDIR /app
      COPY . .
      RUN make build
      
      # ---------- Stage 2: Producer Container ----------
      FROM registry.redhat.io/ubi9-minimal@sha256:30bbd445046a3a63f5f5557a3c67dee74e3c8e7855eb0347630b020f3689823f AS ucm-producer

      RUN mkdir -p /docker/starlight/config_files_starlight/ && \
          mkdir -p /processing_data/ && \
          chmod -R 777 /processing_data/
      
      WORKDIR /processing_data/
      
      COPY --from=builder /app/build/ucm /usr/bin/ucm
      COPY data/. /docker/starlight/config_files_starlight/

      EXPOSE 5672

      ENTRYPOINT ["./uid_entrypoint.sh"]
      CMD ["producer"]
      
      # ---------- Stage 3: Receiver Container ----------
      FROM registry.redhat.io/ubi9-minimal@sha256:30bbd445046a3a63f5f5557a3c67dee74e3c8e7855eb0347630b020f3689823f AS ucm-receiver
      

      RUN microdnf install -y shadow-utils && \
          groupadd -g 1001 ucm && \
          useradd -u 1001 -g ucm -d /home/ucm -s /sbin/nologin ucm
      
      RUN mkdir -p /processing_data && \
          chown -R ucm:ucm /processing_data && \
          chmod -R 775 /processing_data
      
      COPY --from=builder /app/build/ucm /usr/bin/ucm

      
      EXPOSE 5672
      
      LABEL io.k8s.display-name="UCM Application" \
            io.k8s.description="Application interface to UC." \
            maintainer="kromashk@redhat.com"
 
      ENTRYPOINT ["./uid_entrypoint.sh"]
      CMD ["receiver"]